# Generated by Django 5.2.7 on 2025-10-03 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='block_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='plot',
            name='facing_direction',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='plot',
            name='is_corner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plot',
            name='length_ft',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='plot',
            name='plot_type',
            field=models.CharField(choices=[('commercial', 'Commercial'), ('residential', 'Residential')], default='residential', max_length=20),
        ),
        migrations.AddField(
            model_name='plot',
            name='price_per_sqft',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='plot',
            name='size_sqft',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='plot',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='plot',
            name='width_ft',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='plot',
            name='size_sq_yards',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
