# Generated by Django 5.2.7 on 2025-10-06 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0002_plot_block_name_plot_facing_direction_plot_is_corner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installmentplan',
            name='interest_rate',
        ),
    ]
