# Generated by Django 5.2.7 on 2025-10-07 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0003_remove_installmentplan_interest_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installmentplan',
            name='down_payment_percent',
        ),
    ]
