# Generated by Django 5.2.7 on 2025-10-07 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_remove_booking_plan_booking_installment_months'),
        ('plots', '0004_remove_installmentplan_down_payment_percent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InstallmentPlan',
        ),
        migrations.RemoveField(
            model_name='plot',
            name='size_sq_yards',
        ),
    ]
