# Generated by Django 5.2.7 on 2025-10-11 04:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('development', 'Development Cost'), ('marketing', 'Marketing & Ads'), ('maintenance', 'Maintenance'), ('commission', 'Agent Commission'), ('utility', 'Utility Bills'), ('misc', 'Miscellaneous')], default='misc', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
