# Generated by Django 5.2.7 on 2025-10-29 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_booking_source'),
        ('expenses', '0002_expensecategory_alter_expense_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='source',
            field=models.ForeignKey(blank=True, help_text='Select how this expense was paid (e.g., Cash, Bank)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='bookings.paymentsource'),
        ),
    ]
