# Generated by Django 5.2.7 on 2026-01-17 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_expense_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='type',
            field=models.CharField(choices=[('expense', 'Expense'), ('debit', 'Debit'), ('credit', 'Credit')], default='expense', max_length=10),
        ),
    ]
