# Generated by Django 5.2.7 on 2025-10-06 11:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('father_name', models.CharField(max_length=100, verbose_name="Father's Name")),
                ('contact_no', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Contact number must be exactly 11 digits.', regex='^\\d{11}$')], verbose_name='Phone Number')),
                ('cnic', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message='CNIC must be exactly 16 digits.', regex='^\\d{16}$')], verbose_name='CNIC Number')),
                ('address', models.TextField(verbose_name='Address')),
                ('inheritor', models.CharField(max_length=100, verbose_name="Inheritor's Name")),
                ('inheritor_cnic', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Inheritor CNIC must be exactly 16 digits.', regex='^\\d{16}$')], verbose_name="Inheritor's CNIC")),
                ('inheritor_relation', models.CharField(max_length=50, verbose_name='Relation with Inheritor')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
        ),
    ]
