# Generated by Django 5.2.7 on 2025-10-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='cnic',
            field=models.CharField(max_length=16, unique=True, verbose_name='CNIC Number'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='contact_no',
            field=models.CharField(verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='inheritor_cnic',
            field=models.CharField(max_length=16, verbose_name="Inheritor's CNIC"),
        ),
    ]
