# Generated by Django 5.2.7 on 2025-11-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_buyer_cnic_alter_buyer_contact_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='inheritor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Inheritor's Name"),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='inheritor_cnic',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name="Inheritor's CNIC"),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='inheritor_relation',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Relation with Inheritor'),
        ),
    ]
