# Generated by Django 5.2.7 on 2025-10-29 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_paymentsource_payment_source'),
        ('reports', '0002_paymentsource_transaction_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='bookings.paymentsource'),
        ),
        migrations.DeleteModel(
            name='PaymentSource',
        ),
    ]
