# Generated by Django 5.2.7 on 2025-10-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='commission_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Commission Paid'),
        ),
    ]
