# Generated by Django 5.2.7 on 2025-10-07 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_commission_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='plan',
        ),
        migrations.AddField(
            model_name='booking',
            name='installment_months',
            field=models.IntegerField(default=24),
        ),
    ]
