# Generated by Django 5.2.7 on 2025-10-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0004_remove_booking_plan_booking_installment_months"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="received_by",
            field=models.CharField(
                choices=[("tasawur", "Tasawur"), ("abdul_ghafoor", "Abdul Ghafoor")],
                default="abdul_ghafoor",
                max_length=50,
            ),
        ),
    ]
