# Generated by Django 5.2.7 on 2025-10-29 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_paymentsource_payment_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='bookings.paymentsource', verbose_name='Payment Source'),
        ),
    ]
